run_name: lunch
branch: main

platform:
  link: torque
  path_od3d: /misc/lmbweb/essen
  pull_od3d: True
  pull_od3d_submodules: True
  install_od3d: True
  #path_datasets: /misc/lmbraid19/sommerl/datasets
  #path_exps: /misc/lmbraid19/sommerl/exps
  #path_datasets: /misc/lmbraid19/sommerl/datasets
  #path_exps: /misc/lmbraid19/sommerl/exps
  path_cuda: /misc/software/cuda/cuda-11.7
  path_home: /home/sommerl
  url_od3d: git@github.com:lmb-freiburg/meal2023.git
  username: sommerl
  gpu_count: 1
  cpu_count: 8
  ram: "40gb"
  walltime: "24:00:00"

platform_local:
  link: local
  path_home: /home/sommerl
  path_logs: /home/sommerl
  path_od3d: /misc/lmbweb/essen
  #path_datasets: /scratch/sommerl/datasets
  #path_exps: /scratch/sommerl/exps
  #path_datasets: /misc/lmbraid19/sommerl/datasets
  #path_exps: /misc/lmbraid19/sommerl/exps
  #path_cudas: /scratch/sommerl/cudas
  path_cuda: /misc/software/cuda/cuda-11.7
  url_od3d: git@github.com:lmb-freiburg/meal2023.git

